---
- name: Report VM Drive Size
  hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo
  any_errors_fatal: false
  tasks:

    - name: Perform ping in Template
      ping:
    - block:
        - debug:
            var: ansible_play_hosts_all
        - debug:
            var: ansible_play_hosts
        - set_fact:
            down: "{{ ansible_play_hosts_all|difference(ansible_play_hosts) }}"
        - debug:
            var: down
      run_once: true
    - name: Disk usage from command module
      ansible.builtin.shell: "df -k -h --output=pcent / | sed 1d"
      register: size
    - name: Report Disk Percentage to Discord
      community.general.discord:
        webhook_id: "1269357115387023421"
        webhook_token: "STlO37fWLv7COniVYGetviEYySAhkko9hHAmhwT6hCzOfuAR4FAsVeBv41mX5t0NlxRQ"
        content: "Nightly VM Disk Consumption Report \r {{ansible_hostname}} ({{inventory_hostname}}): {{size.stdout}} full"
    - name: Report Unreachable Hosts to Discord
      run_once: true
      community.general.discord:
        webhook_id: "1269357115387023421"
        webhook_token: "STlO37fWLv7COniVYGetviEYySAhkko9hHAmhwT6hCzOfuAR4FAsVeBv41mX5t0NlxRQ"
        content: "These Hosts Are Unreachable: {{down}}"
