---
- hosts: all
  become: yes
  become_user: root
  
  tasks:
    - name: APT Package Updater
      apt:
        upgrade: yes
        update_cache: yes
    - name: Reboot the machine (Wait for 5 min)
      reboot:
        reboot_timeout: 300
