---
- name: Reinstall NPM
  hosts: all
  gather_facts: no
  become: true
 
  tasks:
    - name: remove package
      apt: name=npm state=absent
    - name: install package
      apt: name=npm state=present update_cache=yes
