---
- name: Update DNS
  hosts: all
  gather_facts: no
  become: true

  tasks:
  - name: Pinging Hosts
    ansible.builtin.ping:
  - name: Grab Key
    command: "cat /etc/token/github.token"
    register: key_content
  - name: Fetch Github DNS data
    ansible.builtin.get_url:
      url: "https://github.com/thefirebuilds/dns/blob/d31b27d9b9d79ea8aaef60b184e0a301d72a4081/custom.list"
      dest: /etc/token
      password: '{{ key_content.stdout }}'
