---
- name: Update DNS
  hosts: all
  gather_facts: no
  become: true

  tasks:
  - name: Pinging Hosts
    ansible.builtin.ping:
  - name: Grab Key
    command: "cat /etc/token/github.token"
    register: key_content
  - name: Fetch Github DNS data
    uri:
      url: "https://github.com/thefirebuilds/dns/blob/d31b27d9b9d79ea8aaef60b184e0a301d72a4081/custom.list"
      method: GET
      headers:
        Authorization: token {{key_content.stdout}}
        Accept: application/vnd.github.v3.raw        
