---
- name: Update DNS
  hosts: all
  gather_facts: no
  become: true

  tasks:
  - name: Pinging Hosts
    ansible.builtin.ping:
  - name: Grab Key
    command: "cat /etc/token/github.token"
    register: key_content
  - name: Print the gateway for each host when defined
    ansible.builtin.debug:
      msg: System {{ key_content }}
    when: ansible_default_ipv4.gateway is defined
  - name: Fetch Github DNS data
    uri:
      url: 'https://raw.githubusercontent.com/thefirebuilds/dns/main/custom.list'
      dest: "/etc/pihole/custom.list"
      method: GET
      headers:
        Authorization: 'token {{key_content.stdout}}'
        Accept: application/vnd.github.v3.raw
      follow_redirects: safe
    register: result
  - name: Restart DNS Server
    ansible.builtin.command: pihole restartdns
