---
- hosts: all
  become: true
  become_method: su
  tasks:
    - name: Update Apt List & Upgrade
      apt:
        update_cache: yes
        upgrade: yes
    - name: Reboot the machine (Wait for 5 min)
      reboot:
        reboot_timeout: 300
