---
- name: Update DNS
  hosts: all
  gather_facts: no
  become: true

  tasks:
  - name: Pinging Hosts
    ansible.builtin.ping:
  - name: Grab Key
    command: "cat /etc/token/github.token"
    register: key_content
  - name: Fetch Github DNS data
    uri:
      url: 'https://raw.githubusercontent.com/thefirebuilds/dns/main/custom.list'
      dest: "/home/pihole/etc-pihole/custom.list"
      method: GET
      headers:
        Authorization: 'token {{ key_content.stdout}}'
        Accept: application/vnd.github.v3.raw
      follow_redirects: safe
    register: result
  - name: Restart PiHole inside docker container
    community.docker.docker_container_exec:
      container: pihole
      command: /bin/bash -c "pihole restartdns"
